### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lastmjs** [cwbuecheler/node-tutorial-2-restful-app#3]
Do you have a license for this repo?

**Comment by cwbuecheler** [comment]
Not at present, but this repo will be removed soon in favor of a new, updated one when I launch my new project. All repos associated with that project will have licenses.

**Comment by lastmjs** [comment]
I'm linking to this fork without a license then: https://github.com/scramjs/node-tutorial-2-restful-app Is that alright?

**Comment by cwbuecheler** [comment]
Yes, that's not a problem. Thank you for checking.

**Comment by kamranayub** [comment]
Was considering using this as a reference example for a course I'm working on but wanted to double check the licensing... I don't mind looking elsewhere if you don't intend to license this, but just wanted to make sure since this is a great intro tutorial example 🥇

**Comment by cwbuecheler** [comment]
Discussed this privately. Closing this issue for now. This repo will be revamped or possibly replaced entirely in the next couple of months when I launch CloseBrace.com.
